apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: wavefront-collector
    name: wavefront-collector
  name: wavefront-collector
  namespace: wavefront-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: wavefront-collector
  template:
    metadata:
      labels:
        k8s-app: wavefront-collector
    spec:
      serviceAccountName: wavefront-collector
      containers:
      - name: wavefront-collector
        image: wavefronthq/wavefront-kubernetes-collector:latest
        imagePullPolicy: Always
        command:
        - /wavefront-collector
        - --source=kubernetes.summary_api:''
        - --source=prometheus:''?url=http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics
        - --sink=wavefront:?server=https://YOUR_INSTANCE.wavefront.com&token=YOUR_TOKEN&clusterName=k8s-cluster&includeLabels=true
        - --v=2
        
